Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -35,7 +35,7 @@ jobs:
         echo "Current version: $VERSION"
         echo "VERSION=$VERSION" >> $GITHUB_ENV
 
-    - name:  Update new version in pom.xml
+    - name: Calculate new version
       id: calculate_version
       run: |
         IFS='.' read -r -a version_parts <<< "${{ env.VERSION }}"
@@ -44,9 +44,18 @@ jobs:
         NEW_VERSION="${version_parts[0]}.${version_parts[1]}.$NEW_PATCH"
         echo "New version: $NEW_VERSION"
         echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
+
+    - name: Update version in pom.xml
+      run: |
+        # Backup the existing pom.xml
+        cp pom.xml pom.xml.bak
+        
         # Update the version directly using sed
         sed -i "s/<version>${{ env.VERSION }}<\/version>/<version>${{ env.NEW_VERSION }}<\/version>/g" pom.xml
         
+        # Verify that the version was updated
+        grep "<version>${{ env.NEW_VERSION }}</version>" pom.xml || { echo "Version update failed"; exit 1; }
+
     - name: Build with Maven
       run: mvn -B package --file pom.xml
 
@@ -58,6 +67,11 @@ jobs:
         git add pom.xml
         git commit -m 'Increment patch version' || echo "No changes to commit"
         git push
+
+    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
+    # - name: Update dependency graph
+    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
+
 
     # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
     # - name: Update dependency graph
