Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -20,46 +20,48 @@ jobs:
         java-version: '17'
         distribution: 'temurin'
         cache: maven
+    - name: Automated Maven Version Bump
+      id: bump
+      uses: mickem/gh-action-bump-maven-version@v1.0.0
+   # - name: Get current version
+   #   id: get_version
+   #   run: |
+   #     VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
+   #     echo "Current version: $VERSION"
+   #     echo "VERSION=$VERSION" >> $GITHUB_ENV
 
-    - name: Get current version
-      id: get_version
-      run: |
-        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
-        echo "Current version: $VERSION"
-        echo "VERSION=$VERSION" >> $GITHUB_ENV
+   # - name: Calculate new version
+   #   id: calculate_version
+   #   run: |
+   #     IFS='.' read -r -a version_parts <<< "${{ env.VERSION }}"
+   #     PATCH=${version_parts[2]}
+   #     NEW_PATCH=$((PATCH + 1))
+   #     NEW_VERSION="${version_parts[0]}.${version_parts[1]}.$NEW_PATCH"
+   #     echo "New version: $NEW_VERSION"
+   #     echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
 
-    - name: Calculate new version
-      id: calculate_version
-      run: |
-        IFS='.' read -r -a version_parts <<< "${{ env.VERSION }}"
-        PATCH=${version_parts[2]}
-        NEW_PATCH=$((PATCH + 1))
-        NEW_VERSION="${version_parts[0]}.${version_parts[1]}.$NEW_PATCH"
-        echo "New version: $NEW_VERSION"
-        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
-
-    - name: Update version in pom.xml
-      run: |
-        # Backup the existing pom.xml
-        cp pom.xml pom.xml.bak
+  #  - name: Update version in pom.xml
+   #   run: |
+   #     # Backup the existing pom.xml
+   #     cp pom.xml pom.xml.bak
         
-        # Update the version directly using sed
-        sed -i "s/<version>${{ env.VERSION }}<\/version>/<version>${{ env.NEW_VERSION }}<\/version>/g" pom.xml
+  #      # Update the version directly using sed
+ #       sed -i "s/<version>${{ env.VERSION }}<\/version>/<version>${{ env.NEW_VERSION }}<\/version>/g" pom.xml
         
-        # Verify that the version was updated
-        grep "<version>${{ env.NEW_VERSION }}</version>" pom.xml || { echo "Version update failed"; exit 1; }
+ #       # Verify that the version was updated
+ #       grep "<version>${{ env.NEW_VERSION }}</version>" pom.xml || { echo "Version update failed"; exit 1; }
 
  #   - name: Build with Maven
  #    run: mvn -B package --file pom.xml
 
-    - name: Commit version changes
-      if: github.ref == 'refs/heads/master'
-      run: |
-        git config --global user.name 'GitHub Actions'
-        git config --global user.email 'actions@github.com'
-        git add pom.xml
-        git commit -m 'Increment patch version' || echo "No changes to commit"
-        git push
+   #  - name: Commit version changes
+    #   if: github.ref == 'refs/heads/master'
+     #  run: |
+    #     git config --global user.name 'GitHub Actions'
+    #    git config --global user.email 'actions@github.com'
+   #      git add pom.xml
+   #     git commit -m 'Increment patch version' || echo "No changes to commit"
+  #      git push
 
     - name: Login to Docker Hub
       uses: docker/login-action@v3
