Update maven_1.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -5,7 +5,6 @@
 # They are provided by a third-party and are governed by
 # separate terms of service, privacy policy, and support
 # documentation.
-
 name: Java CI with Maven
 
 on:
@@ -48,23 +47,31 @@ jobs:
 
     - name: Update version in pom.xml
       run: |
-        mvn versions:set -DnewVersion=${{ env.NEW_VERSION }} -DgenerateBackupPoms=false
+        # Backup the existing pom.xml
+        cp pom.xml pom.xml.bak
+        
+        # Update the version directly using sed
+        sed -i "s/<version>${{ env.VERSION }}<\/version>/<version>${{ env.NEW_VERSION }}<\/version>/g" pom.xml
+        
+        # Verify that the version was updated
+        grep "<version>${{ env.NEW_VERSION }}</version>" pom.xml || { echo "Version update failed"; exit 1; }
 
     - name: Verify version change
       run: |
+        # Check for differences in pom.xml
         git diff pom.xml
-        if ! git diff --quiet; then
-          echo "pom.xml has been updated with the new version."
-        else
-          echo "No changes to pom.xml. Exiting."
+        if git diff --quiet; then
+          echo "No changes detected in pom.xml. Exiting."
           exit 1
+        else
+          echo "pom.xml has been updated."
         fi
 
     - name: Build with Maven
       run: mvn -B package --file pom.xml
 
     - name: Commit version changes
-      if: github.ref == 'refs/heads/master' && steps.get_version.outputs.VERSION != steps.calculate_version.outputs.NEW_VERSION
+      if: github.ref == 'refs/heads/master'
       run: |
         git config --global user.name 'GitHub Actions'
         git config --global user.email 'actions@github.com'
@@ -75,9 +82,3 @@ jobs:
     # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
     # - name: Update dependency graph
     #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
-
-
-    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
-    #- name: Update dependency graph
-     
-     # uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
